resources:
  - name: src_repo_conan_examples2
    type: GitRepo
    configuration:
      path: harshkumar1/conan-examples2
      files:
        include: tutorial/consuming_packages/simple_cmake_project
      gitProvider: hk_github
      branches:
        include: ^main$
      cloneProtocol: https
      buildOn:
        commit: true

pipelines:
  - name: demo_conan_pipeline_example
    steps:
      - name: compile
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: pipelines.jfrog.io/pipelines-runtime-images/pipelines-w19cpp-ckmake
                tag: '1'
          inputResources:
            - name: src_repo_conan_examples2
        execution:
          onStart:
            - pip install conan
          onExecute:
            - cd $res_src_repo_conan_examples2_resourcePath/tutorial/consuming_packages/simple_cmake_project
            - ls -l
            - conan profile detect --force
            - conan install . --output-folder=build --build=missing
            - cd build
            - cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
            - cmake --build .
            - pwd
            - ls -l
          onSuccess:
            - add_run_files $res_src_repo_conan_examples2_resourcePath/tutorial/consuming_packages/simple_cmake_project/build simple_cmake_project_build
      - name: publish
        type: Bash
        configuration:
          inputSteps:
            - name: compile
        execution:
          onStart:
            - restore_run_files simple_cmake_project_build simple_cmake_project_build/
            - pwd
            - ls -l
          onExecute:
            - echo "publish step"