resources:
  - name: src_repo_conan_examples2
    type: GitRepo
    configuration:
      path: harshkumar1/conan-examples2
      files:
        include: tutorial/consuming_packages/simple_cmake_project
      gitProvider: hk_github
      branches:
        include: ^main$
      cloneProtocol: https
      buildOn:
        commit: true
  - name: demo_conan_pipeline_example_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: hk_artifactory_1
      buildName: demo_conan_pipeline_example
      buildNumber: ${run_number}

pipelines:
  - name: demo_conan_pipeline_example
    configuration:
      jfrogCliVersion: '2'
      integrations:
        - name: hk_artifactory_1
    steps:
      - name: compile
        type: Bash
        configuration:
          affinityGroup: conan_compile_scan
          runtime:
            type: image
            image:
              custom:
                name: pipelines.jfrog.io/pipelines-runtime-images/pipelines-w19cpp-ckmake
                tag: '1'
          inputResources:
            - name: src_repo_conan_examples2
            - name: demo_conan_pipeline_example_build_info
        execution:
          onStart:
            - pip install conan
          onExecute:
            - cd $res_src_repo_conan_examples2_resourcePath/tutorial/consuming_packages/simple_cmake_project
            - conan profile detect --force
            - conan install . --output-folder=build --build=missing
            - cd build
            - cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
            - cmake --build .
          onSuccess:
            - add_run_files $res_src_repo_conan_examples2_resourcePath/tutorial/consuming_packages/simple_cmake_project/build simple_cmake_project_build
            #- write_output demo_conan_pipeline_example_build_info buildName=demo_conan_pipeline_example buildNumber=${run_number}

      - name: publish
        type: PublishBuildInfo
        configuration:
          affinityGroup: conan_compile_scan
          inputSteps:
            - name: compile
          outputResources:
            - name: demo_conan_pipeline_example_build_info
          forceXrayScan: true
          failOnScan: true
        execution:
          onSuccess:
            - echo "publishing artifact"  
            - restore_run_files simple_cmake_project_build simple_cmake_project_build/
            - jf rt upload --flat=true simple_cmake_project_build/compressor generic-repo-local/simple_cmake_project_build/${run_number}/
